### ISSUE TITLE
line:210 char:9

### ISSUE THREAD

**Issue by mikerodionov** [timmes/K2Field.PreReq#6]
It seems that "line:210 char:9":

$path = Split-Path -parent $MyInvocation.MyCommand.Definition 

fails if script is being executed from **NOT** saved file, e.g. immediately after pasting into PowerShell ISE Script Pane without prior saving. I think it can be mitigated somehow...

**Comment by timmes** [comment]
Can you check again. I did some changes to the script. Maybe the issue was directly solved with it. If not, I'll re-check again. Cheers!

**Comment by timmes** [comment]
Checked and the issue is still there but it's obvious because the script doesn't have any location and is just in the temp memory when it's **NOT** saved. Only thing I can imagine of is to take the path for the CSV file as an input parameter.

**Comment by mikerodionov** [comment]
Well checking this only now and it seems that now it does not work for me at all... Will update you with details later once I do some more testing
